### ISSUE TITLE
Errors from the bot

### ISSUE THREAD

**Issue by dkoz** [nminchow/black-book#8]
Errors reporting:
```
error fetching api data
FetchError: request to https://d4armory.io/api/events/recent failed, reason: socket hang up
    at ClientRequest.<anonymous> (file:///home/user/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketOnEnd (node:_http_client:478:9)
    at TLSSocket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: undefined
} 
```

```
error fetching api data
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Response.json (file:///home/user/node_modules/node-fetch/src/body.js:149:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
doing event checks
```

**Comment by nminchow** [comment]
yeah, if the api goes down this will happen. That said, the bot should handle it gracefully. Was it not? Do you think we need more graceful error handling?
